### ISSUE TITLE
What-s-New-in-PowerShell-Core-62.md is broken

### ISSUE THREAD

**Issue by stknohg** [MicrosoftDocs/powerShell-Docs.ja-jp#18]
The automatically translated content is cut off in the middle.

* https://github.com/MicrosoftDocs/powerShell-Docs.ja-jp/blob/live/reference/docs-conceptual/whats-new/What-s-New-in-PowerShell-Core-62.md

**Comment by CeciAc** [comment]
Hello, @stknohg
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @stknohg

Thank you for your feedback.
 
Our engineer team reviewed your suggestions and accepted them. We implemented your feedback and published to the updated articles on the Docs site to the following pages https://github.com/MicrosoftDocs/powerShell-Docs.ja-jp/blob/live/reference/docs-conceptual/whats-new/What-s-New-in-PowerShell-Core-62.md

We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback.

Kind regards,
Microsoft DOCS International Team
