### ISSUE TITLE
[LOC] Broken link "リモート エンドポイントの作成方法"

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/powerShell-Docs.ja-jp#19]
ja-jp:https://docs.microsoft.com/ja-jp//powershell/scripting/install/installing-powershell-core-on-windows?view=powershell-6
![installing-powershell-core-on-windows_j](https://user-images.githubusercontent.com/40815708/58065661-6d0d3f00-7bc1-11e9-8796-d36184ed5e74.png)

en-us:https://docs.microsoft.com/en-us/powershell/scripting/install/installing-powershell-core-on-windows?view=powershell-6
![installing-powershell-core-on-windows_e](https://user-images.githubusercontent.com/40815708/58065669-77c7d400-7bc1-11e9-9cab-a114bcaecaef.png)

**Comment by CeciAc** [comment]
こんにちは、@hyoshioka0128

フィードバックをお送りいただきありがとうございました。 

コメントを確認中で、改めてご連絡させていただきます。 

敬具 
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
こんにちは、@hyoshioka0128
フィードバックをお送りいただきありがとうございました。 
 Microsoft のエンジニア リング チームでは、ご提案いただいた内容を検証し、それを受け入れることになりました。お寄せいただいたフィードバックを実装し、ドキュメント サイト上の次のページの更新された記事に公開しました: https://docs.microsoft.com/ja-jp//powershell/scripting/install/installing-powershell-core-on-windows?view=powershell-6
 記事の品質向上にご協力いただき誠にありがとうございました。引き続きお客様からの貴重なフィードバックをお待ちしています。 
 敬具 
Microsoft DOCS International Team
